import { GAME_CONSTANTS } from 'football-manager-shared/src/constants/game'

export const SIMULATION_CONSTANTS = {
  TEAM_STRENGTH: GAME_CONSTANTS.TEAM_STRENGTH,
  MATCH: {
    DURATION: GAME_CONSTANTS.MATCH.DURATION,
    EVENT_PROBABILITY: GAME_CONSTANTS.MATCH.EVENT_PROBABILITY,
    GOAL_PROBABILITY: GAME_CONSTANTS.MATCH.GOAL_PROBABILITY,
    REALTIME_DELAY_MS: GAME_CONSTANTS.MATCH.REALTIME_DELAY_MS
  }
} as const
